name: timer_app_08
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.7
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  numberpicker: ^2.1.1
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.0.15
  expandable_page_view: ^1.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
